### ISSUE TITLE
fix/폰트 스타일명(text->font) 수정

### ISSUE THREAD

**Issue by myong39** [vivi-trip/vivitrip#77]
> todo
- [x] 폰트 스타일명(text->font) 수정

- 이유 : tailwind-merge 가 text- 처럼 같은 블록으로 시작할 경우에 가장 마지막에 선언되어있는 클래스로 사용되어 먼저 선언된 클래스가 무시됨(주혁님이 발견)
- 처리 : globals.css에서 설정된 폰트 스타일을 예시 text-24px-bold 에서 font-24px-bold 로 수정

**Comment by JuhyeokC** [comment]
@kanghyosung1 
효성님! 작업하신 파일에 해당 내용 적용 부탁드리겠습니다!
